### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by supaboi21** [ISA-Manipal-Chapter/ROS-Workshop#1]
# Issue 1
#### Day1:
- Basic Nodes
- Subscriber, Publisher
- Messages and Services
#### Day 2:
- Launch files
- Visualisation and debugging tools
- Visualising sensor data
- TF(Transformations)
#### Day 3:
- 3D Robot Modelling
- Gazebo (basics)

**Comment by TheProjectsGuy** [comment]
All discussions regarding this on the gitter [chatroom](https://gitter.im/ISA-Manipal/ROS_Workshop?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
